// BYOK : chaque clé reste dans le navigateur de son propriétaire.
const PROVIDERS={
 openrouter:{key:'codewolf_key_openrouter',models:{free:'openrouter/free',paid:'anthropic/claude-sonnet-4'},schema:true,kind:'openai',url:'https://openrouter.ai/api/v1/chat/completions'},
 mistral:{key:'codewolf_key_mistral',models:{free:'mistral-small-latest',paid:'mistral-large-latest'},schema:false,kind:'openai',url:'https://api.mistral.ai/v1/chat/completions'},
 openai:{key:'codewolf_key_openai',models:{free:'gpt-4o-mini',paid:'gpt-4o'},schema:true,kind:'openai',url:'https://api.openai.com/v1/chat/completions'},
 anthropic:{key:'codewolf_key_anthropic',models:{free:'claude-haiku-4-5',paid:'claude-sonnet-5'},schema:false,kind:'anthropic',url:'https://api.anthropic.com/v1/messages'},
 gemini:{key:'codewolf_key_gemini',models:{free:'gemini-2.5-flash',paid:'gemini-2.5-pro'},schema:false,kind:'gemini'}
};
export const DEFAULT_PROVIDER_ORDER=['mistral','gemini','openrouter','anthropic','openai'];
const providerQueues={},lastRequestAt={};async function waitForProvider(name){const minimum=name==='mistral'?1100:120;const previous=providerQueues[name]||Promise.resolve();providerQueues[name]=previous.catch(()=>{}).then(async()=>{const wait=Math.max(0,minimum-(Date.now()-(lastRequestAt[name]||0)));if(wait)await new Promise(r=>setTimeout(r,wait));lastRequestAt[name]=Date.now()});await providerQueues[name]}
export function getProviderOrder(){let saved=[];try{saved=JSON.parse(localStorage.getItem('codewolf_provider_priority')||'[]')}catch{}return [...new Set([...saved.filter(x=>PROVIDERS[x]),...DEFAULT_PROVIDER_ORDER])]}
export async function callWolfyAgent(history,memory,tier='free',reasoning=5,language='fr',options={}){
 const system=`Tu es Wolfy, mentor expert en HTML, CSS et JavaScript. Réponds en ${language==='fr'?'français':'anglais'} avec bienveillance et précision. Profil: ${JSON.stringify(memory)}. Détail: ${reasoning}/20. ${options.json?'Produis exclusivement un objet JSON valide, sans Markdown, commentaire ni texte autour.':'Utilise Markdown.'}`;let last='aucune clé API configurée';
 for(const name of getProviderOrder()){const p=PROVIDERS[name],key=localStorage.getItem(p.key);if(!key)continue;try{await waitForProvider(name);const {url,init}=buildRequest(name,p,key,history,system,tier,options),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),90000),res=await fetch(url,{...init,signal:controller.signal});clearTimeout(timer);if(!res.ok){let detail='';try{const err=await res.json();detail=err.error?.message||err.message||''}catch{}last=`${name}: erreur ${res.status}${detail?' — '+detail:''}`;continue}const data=await res.json(),text=extractText(p.kind,data);if(text)return text;last=`${name}: réponse vide`}catch(e){last=e.name==='AbortError'?`${name}: délai dépassé`:e.message}}
 if(options.json)throw new Error(last);return `⚠️ Wolfy est hors ligne (${last}). Vérifie ta clé et l’ordre des fournisseurs.`
}
function buildRequest(name,p,key,history,system,tier,options){const model=p.models[tier]||p.models.free;if(p.kind==='anthropic')return {url:p.url,init:{method:'POST',headers:{'x-api-key':key,'anthropic-version':'2023-06-01','anthropic-dangerous-direct-browser-access':'true','content-type':'application/json'},body:JSON.stringify({model,max_tokens:options.json?6000:1800,temperature:options.json?.1:.65,system,messages:history.filter(m=>m.role!=='system').map(m=>({role:m.role==='assistant'?'assistant':'user',content:String(m.content)}))})}};if(p.kind==='gemini'){const generationConfig={temperature:options.json?.1:.65,maxOutputTokens:options.json?6000:1800};if(options.json)generationConfig.responseMimeType='application/json';return {url:`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${encodeURIComponent(key)}`,init:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({systemInstruction:{parts:[{text:system}]},contents:history.filter(m=>m.role!=='system').map(m=>({role:m.role==='assistant'?'model':'user',parts:[{text:String(m.content)}]})),generationConfig})}}}const body={model,messages:[{role:'system',content:system},...history],temperature:options.json?.1:.65,max_tokens:options.json?6000:1800};if(options.schema&&p.schema)body.response_format={type:'json_schema',json_schema:{name:options.schemaName||'codewolf_response',strict:true,schema:options.schema}};else if(options.json)body.response_format={type:'json_object'};const headers={Authorization:`Bearer ${key}`,'Content-Type':'application/json'};if(name==='openrouter'){headers['HTTP-Referer']=location.origin;headers['X-Title']='CodeWolf'}return {url:p.url,init:{method:'POST',headers,body:JSON.stringify(body)}}}
function extractText(kind,data){if(kind==='anthropic')return data.content?.map(x=>x.text||'').join('')||'';if(kind==='gemini')return data.candidates?.[0]?.content?.parts?.map(x=>x.text||'').join('')||'';return data.choices?.[0]?.message?.content||''}
