import {callWolfyAgent} from './aiClient.js';
import {createAssessmentSession,updateAssessment} from './pedagogyCloudClient.js';
import {parseAiJson} from './jsonUtils.js';
const $=s=>document.querySelector(s);let profile={};try{profile=JSON.parse(localStorage.getItem('codewolf_student_memory')||'{}')}catch{}const completeBeginner=/début|jamais|aucune/i.test(profile.level||'');let transcript=[],current=null,count=0,target=completeBeginner?5:7,assessmentId=null;
$('#assessmentKey').value=localStorage.getItem('codewolf_key_openrouter')||'';$('#startAssessment').onclick=async()=>{const key=$('#assessmentKey').value.trim();if(key)localStorage.setItem('codewolf_key_openrouter',key);if(!key&&!localStorage.getItem('codewolf_key_openai')){alert('Ajoute une clé OpenRouter ou configure une clé OpenAI depuis le dashboard.');return}$('#setupCard').hidden=true;$('#questionCard').hidden=false;try{assessmentId=await createAssessmentSession()}catch(e){console.warn('Évaluation locale:',e.message)}await nextQuestion()};
async function nextQuestion(){count++;$('#assessmentStep').textContent=`Question ${count} sur environ ${target}`;$('#questionNumber').textContent=`${count} / ${target}`;$('#questionContent').innerHTML='<p class="muted">Wolfy prépare la prochaine question…</p>';$('#answerZone').innerHTML='';$('#submitAnswer').disabled=true;const prompt=`Tu conduis un entretien adaptatif pour un apprenant en développement web. Profil déclaré: ${JSON.stringify(profile)}. Voici les échanges: ${JSON.stringify(transcript)}. Pose la question ${count} sur ${target}. ${completeBeginner?'La personne est débutante absolue : ne lui demande aucun code ni jargon technique. Explore ses objectifs, ce qu’elle pense être un site, ses préférences et son rythme. Le parcours commencera par expliquer Internet, navigateur, frontend, backend, HTML, CSS puis JavaScript.':'Varie progressivement entre expérience, objectifs, HTML, CSS, JavaScript et raisonnement, sans demander une notion jamais introduite.'} Adapte la difficulté. Réponds uniquement en JSON: {"question":"...","kind":"choice|text","choices":["..."]}. Une seule question.`;let raw='';try{raw=await callWolfyAgent([{role:'user',content:prompt}],{},'free',7,'fr',{json:true});current=parseAiJson(raw)}catch(e){console.warn('Question IA indisponible:',e.message);current=fallback(count)}renderQuestion()}
function renderQuestion(){$('#questionContent').innerHTML=DOMPurify.sanitize(`<h2>${current.question}</h2>`);const zone=$('#answerZone');zone.innerHTML='';if(current.kind==='choice'&&current.choices?.length){current.choices.forEach((c,i)=>{const b=document.createElement('button');b.className='quiz-choice';b.innerHTML=DOMPurify.sanitize(`<span>${String.fromCharCode(65+i)}</span>${c}`);b.onclick=()=>{zone.querySelectorAll('button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');b.dataset.value=c;$('#submitAnswer').disabled=false};zone.append(b)})}else{const t=document.createElement('textarea');t.className='assessment-text';t.placeholder='Écris ta réponse ici…';t.oninput=()=>$('#submitAnswer').disabled=!t.value.trim();zone.append(t)}}
$('#submitAnswer').onclick=async()=>{const selected=$('#answerZone .selected'),text=$('#answerZone textarea');const answer=selected?.dataset.value||text?.value.trim();if(!answer)return;transcript.push({question:current.question,answer});updateAssessment(assessmentId,{questions:transcript.map(x=>x.question),answers:transcript.map(x=>x.answer)}).catch(()=>{});if(count<target)await nextQuestion();else await finishInterview()};
async function finishInterview(){
 $('#questionContent').innerHTML=`<h2>J’analyse ton profil…</h2><p class="muted">${completeBeginner?'Je prépare tes premières explications.':'Je calibre la prochaine étape de ton parcours.'}</p>`;$('#answerZone').innerHTML='';$('#submitAnswer').hidden=true;
 const prompt=`Analyse cet entretien: ${JSON.stringify(transcript)}. Profil déclaré: ${JSON.stringify(profile)}. Réponds uniquement en JSON: {"level":"Débutant|Fondamental|Intermédiaire|Avancé","summary":"2 phrases","strengths":["..."],"goals":"...","recommendedSkill":"html.document","challenge":null}. ${completeBeginner?'C’est un débutant absolu : challenge doit rester null. Recommande un parcours théorique et visuel commençant par Internet, navigateur, frontend/backend, puis le rôle de HTML, CSS et JavaScript. Aucun exercice de code avant ces explications.':'Tu peux remplacer challenge par un mini-projet de 15 minutes avec title, brief, requirements et starter si le niveau le justifie. Le starter index.html doit être un document HTML5 complet avec <!DOCTYPE html>, html, head, meta viewport, title, body et les liens vers style.css et script.js.'}`;
 let result;try{const raw=await callWolfyAgent([{role:'user',content:prompt}],profile,'free',10,'fr',{json:true});result=parseAiJson(raw)}catch(e){console.warn('Analyse IA indisponible:',e.message);result={level:completeBeginner?'Débutant':'Fondamental',summary:completeBeginner?'Tu vas commencer sans prérequis. Wolfy t’expliquera d’abord comment fonctionne le Web avant d’écrire la moindre ligne de code.':'Tu possèdes une base prometteuse que le parcours va consolider.',strengths:['Motivation','Curiosité'],goals:'Comprendre et maîtriser le développement web',recommendedSkill:'html.document',challenge:null}}
 if(completeBeginner)result.challenge=null;
 localStorage.setItem('codewolf_assessment_result',JSON.stringify(result));
 if(result.challenge?.starter){localStorage.setItem('codewolf_current_challenge',JSON.stringify(result.challenge));localStorage.setItem('codewolf_workspace',JSON.stringify(result.challenge.starter))}else{localStorage.removeItem('codewolf_current_challenge')}
 const memory={level:result.level,curriculumStep:1,goals:result.goals,progress:0,xp:120,assessmentPending:Boolean(result.challenge),onboardingConceptsPending:!result.challenge};localStorage.setItem('codewolf_student_memory',JSON.stringify(memory));
 updateAssessment(assessmentId,{status:result.challenge?'challenge':'completed',questions:transcript.map(x=>x.question),answers:transcript.map(x=>x.answer),provisional_level:result.level,confirmed_level:result.challenge?null:result.level,confidence:result.confidence||null,skill_estimates:result.skills||{},challenge_data:result.challenge,completed_at:result.challenge?null:new Date().toISOString()}).catch(()=>{});showResult(result)
}
function showResult(r){
 $('#questionCard').hidden=true;const card=$('#resultCard');card.hidden=false;const next=r.challenge?`<div class="challenge-preview"><small>MINI-TEST À FAIRE PLUS TARD</small><h2>${r.challenge.title}</h2><p>${r.challenge.brief}</p></div>`:`<div class="challenge-preview"><small>TA PREMIÈRE ÉTAPE</small><h2>Comprendre comment fonctionne le Web</h2><p>Internet, navigateur, frontend, backend, HTML, CSS et JavaScript — Wolfy va tout reprendre depuis zéro avec des exemples visuels.</p></div>`;card.innerHTML=DOMPurify.sanitize(`<img class="assessment-wolf" src="/assets/wolfy.svg"><span class="eyebrow">TON POINT DE DÉPART</span><h1>${r.level}</h1><p>${r.summary}</p><div class="result-strengths">${(r.strengths||[]).map(x=>`<span>✓ ${x}</span>`).join('')}</div>${next}<button class="btn btn-primary btn-lg" id="assessmentContinue">Découvrir mon parcours →</button>`);card.querySelector('#assessmentContinue').onclick=()=>location.href='/dashboard'
}
function fallback(i){const qs=[['Depuis combien de temps codes-tu ?',['Je débute aujourd’hui','Quelques semaines','Plusieurs mois','Plus d’un an']],['Que veux-tu surtout créer ?',['Sites vitrines','Applications web','Jeux et animations','Je ne sais pas encore']],['À quoi sert HTML ?',['Structurer le contenu','Créer la base de données','Héberger le site']],['Quelle propriété CSS organise facilement des éléments en ligne ?',['display: flex','font-weight','border-radius']],['As-tu déjà manipulé le DOM en JavaScript ?',['Jamais','Un peu','Oui, régulièrement']],['Comment te sens-tu face à une erreur dans la console ?',['Perdu','Je cherche le message','Je sais généralement la diagnostiquer']],['Décris brièvement un projet que tu aimerais réussir.',null]];const q=qs[Math.min(i-1,qs.length-1)];return {question:q[0],kind:q[1]?'choice':'text',choices:q[1]||[]}}