import {basicSetup,EditorView} from 'https://esm.sh/codemirror@6.0.1';
import {EditorState,Compartment} from 'https://esm.sh/@codemirror/state@6.5.2';
import {keymap,highlightActiveLine,highlightActiveLineGutter,drawSelection,dropCursor,rectangularSelection,crosshairCursor} from 'https://esm.sh/@codemirror/view@6.36.5';
import {defaultKeymap,historyKeymap,indentWithTab} from 'https://esm.sh/@codemirror/commands@6.8.1';
import {searchKeymap,highlightSelectionMatches} from 'https://esm.sh/@codemirror/search@6.5.10';
import {autocompletion,completionKeymap,closeBrackets,closeBracketsKeymap} from 'https://esm.sh/@codemirror/autocomplete@6.18.6';
import {foldGutter,foldKeymap,bracketMatching,indentOnInput,syntaxHighlighting,defaultHighlightStyle} from 'https://esm.sh/@codemirror/language@6.10.8';
import {html} from 'https://esm.sh/@codemirror/lang-html@6.4.9';
import {css} from 'https://esm.sh/@codemirror/lang-css@6.3.1';
import {javascript} from 'https://esm.sh/@codemirror/lang-javascript@6.2.3';
import {lintGutter} from 'https://esm.sh/@codemirror/lint@6.8.5';

const language=new Compartment(),readOnly=new Compartment();let view,currentFile='index.html',syncing=false;
function languageFor(name){if(name.endsWith('.html')||name.endsWith('.htm'))return html({autoCloseTags:true});if(name.endsWith('.css'))return css();if(name.endsWith('.js')||name.endsWith('.mjs'))return javascript({jsx:true});return []}
const wolfTheme=EditorView.theme({'&':{height:'100%',backgroundColor:'#0c111a',color:'#cbd5e7',fontSize:'12px'},'.cm-content':{fontFamily:"'DM Mono', monospace",lineHeight:'1.75',padding:'14px 0',caretColor:'#66f7e8'},'.cm-cursor,.cm-dropCursor':{borderLeftColor:'#66f7e8'},'&.cm-focused .cm-selectionBackground,.cm-selectionBackground,.cm-content ::selection':{backgroundColor:'#263c59'},'.cm-gutters':{backgroundColor:'#0a0e16',color:'#3f4b60',border:'none',paddingLeft:'4px'},'.cm-activeLineGutter':{backgroundColor:'#121a28',color:'#8391a9'},'.cm-activeLine':{backgroundColor:'rgba(102,247,232,.025)'},'.cm-foldPlaceholder':{backgroundColor:'#172033',border:'none',color:'#7e8ca5'},'.cm-tooltip':{backgroundColor:'#111827',border:'1px solid #2a3850',color:'#d9e2f0'},'.cm-tooltip-autocomplete ul li[aria-selected]':{backgroundColor:'#1d3045',color:'#66f7e8'},'.cm-panels':{backgroundColor:'#0f1623',color:'#d8e0ed'},'.cm-searchMatch':{backgroundColor:'rgba(244,197,106,.25)',outline:'1px solid rgba(244,197,106,.45)'},'.cm-matchingBracket':{backgroundColor:'rgba(102,247,232,.15)',outline:'1px solid #66f7e8'},'.cm-scroller':{overflow:'auto'}},{dark:true});
const listener=EditorView.updateListener.of(update=>{if(!update.docChanged||syncing)return;const textarea=document.getElementById('activeFileTextarea');textarea.value=update.state.doc.toString();textarea.dispatchEvent(new Event('input',{bubbles:true}));updateStatus(update.state.doc.lines,update.state.selection.main.head)});
function updateStatus(lines,position){const status=document.getElementById('activeContext');if(status){const line=view?.state.doc.lineAt(position);status.textContent=`${currentFile} · Ln ${line?.number||1}, Col ${(position-(line?.from||0))+1} · ${lines} lignes`}}
export async function mountCodeEditor(){const mount=document.getElementById('codeMirrorMount'),textarea=document.getElementById('activeFileTextarea'),area=document.getElementById('codeArea');if(!mount||!textarea)return;const extensions=[basicSetup,keymap.of([...defaultKeymap,...historyKeymap,...searchKeymap,...foldKeymap,...completionKeymap,...closeBracketsKeymap,indentWithTab]),language.of(languageFor(currentFile)),readOnly.of(EditorState.readOnly.of(false)),wolfTheme,syntaxHighlighting(defaultHighlightStyle,{fallback:true}),highlightActiveLine(),highlightActiveLineGutter(),highlightSelectionMatches(),drawSelection(),dropCursor(),rectangularSelection(),crosshairCursor(),foldGutter(),bracketMatching(),closeBrackets(),indentOnInput(),autocompletion({activateOnTyping:true}),lintGutter(),EditorView.lineWrapping,listener];view=new EditorView({state:EditorState.create({doc:textarea.value,extensions}),parent:mount});area.classList.add('codemirror-ready');window.CodeWolfEditor={focus:()=>view.focus(),getValue:()=>view.state.doc.toString(),setValue(value){replaceDocument(value)},undo:()=>document.execCommand('undo'),view};window.addEventListener('codewolf:file-switch',event=>{currentFile=event.detail.name;replaceDocument(event.detail.content);view.dispatch({effects:language.reconfigure(languageFor(currentFile))});updateStatus(view.state.doc.lines,0)});textarea.addEventListener('codewolf:sync',()=>replaceDocument(textarea.value));updateStatus(view.state.doc.lines,0);view.focus()}
function replaceDocument(value=''){if(!view||view.state.doc.toString()===value)return;syncing=true;view.dispatch({changes:{from:0,to:view.state.doc.length,insert:value},selection:{anchor:0}});syncing=false}
