import {callWolfyAgent} from './aiClient.js';
import {getCloudState,syncCloudState,saveSubmission} from './cloudClient.js';
let memory={level:'Débutant',curriculumStep:1,goals:'Maîtriser le développement web',progress:24,xp:120};try{memory={...memory,...JSON.parse(localStorage.getItem('codewolf_student_memory')||'{}')}}catch{}
let history=[],active='index.html';let files={
'index.html':`<main class="quest-card">\n  <span class="tag">MISSION 01</span>\n  <h1>Build the future.</h1>\n  <p>Crée une interface qui donne envie d'explorer.</p>\n  <button id="startBtn">Commencer la quête →</button>\n</main>`,
'style.css':`* { box-sizing: border-box; }\nbody {\n  margin: 0; min-height: 100vh; display: grid; place-items: center;\n  background: #080b14; color: #f2f5fb; font-family: system-ui;\n}\n.quest-card {\n  width: min(420px, 90%); padding: 32px; border-radius: 18px;\n  background: #11182b; border: 1px solid #26324f;\n  box-shadow: 0 25px 70px #0008;\n}\n.tag { color: #66f7e8; font-size: 12px; letter-spacing: .15em; }\nh1 { font-size: 42px; margin: 16px 0 8px; }\np { color: #95a1b8; line-height: 1.6; }\nbutton { padding: 12px 16px; border: 0; border-radius: 9px; background: #66f7e8; font-weight: 700; cursor: pointer; }`,
'script.js':`document.querySelector('#startBtn').addEventListener('click', () => {\n  document.querySelector('#startBtn').textContent = 'Quête lancée ✓';\n  console.log('Mission démarrée !');\n});`};
const $=s=>document.querySelector(s);let cloudTimer;function save(){localStorage.setItem('codewolf_workspace',JSON.stringify(files));localStorage.setItem('codewolf_student_memory',JSON.stringify(memory));clearTimeout(cloudTimer);cloudTimer=setTimeout(()=>syncCloudState(memory,files).catch(e=>console.warn('Cloud sync:',e.message)),1200)}try{files={...files,...JSON.parse(localStorage.getItem('codewolf_workspace')||'{}')}}catch{}
function renderFiles(){const list=$('#fileExplorerList'),tabs=$('#fileTabsContainer');list.innerHTML=tabs.innerHTML='';Object.keys(files).forEach(name=>{const f=document.createElement('div');f.className='file '+(name===active?'active':'');f.textContent=(name.endsWith('.html')?'◇ ':name.endsWith('.css')?'# ':'JS ')+name;f.onclick=()=>switchFile(name);list.append(f);const t=document.createElement('div');t.className='tab '+(name===active?'active':'');t.textContent=name;t.onclick=()=>switchFile(name);tabs.append(t)})}
function switchFile(name){active=name;$('#activeFileTextarea').value=files[name];renderFiles()}
function preview(){const html=files['index.html']||'',css=files['style.css']||'',js=files['script.js']||'';$('#livePreview').srcdoc=`<!doctype html><style>${css}</style>${html}<script>console.log=(...a)=>parent.postMessage({type:'cw-console',message:a.join(' ')},'*');window.onerror=m=>parent.postMessage({type:'cw-console',message:'Erreur: '+m},'*');<\/script><script>${js}<\/script>`}
function append(sender,text){const row=document.createElement('div');row.className='message-row '+sender;if(sender==='wolfy'){const img=document.createElement('img');img.src='/assets/wolfy.svg';row.append(img)}const msg=document.createElement('div');msg.className='message';msg.innerHTML=sender==='wolfy'?(window.DOMPurify?DOMPurify.sanitize(marked.parse(text)):text):'';if(sender!=='wolfy')msg.textContent=text;row.append(msg);$('#chatMessages').append(row);$('#chatMessages').scrollTop=1e9}
async function ask(text,shown=text){append('user',shown);history.push({role:'user',content:text});const wait=document.createElement('div');wait.className='thinking-indicator';wait.textContent='Wolfy réfléchit…';$('#chatMessages').append(wait);const answer=await callWolfyAgent(history,memory,'free',5,'fr');wait.remove();history.push({role:'assistant',content:answer});append('wolfy',answer);return answer}
window.sendMessage=async()=>{const el=$('#userInput'),text=el.value.trim();if(!text)return;el.value='';await ask(text);memory.xp+=5;update();save()};window.requestHint=()=>ask(`Donne-moi un indice bref sur mon projet actuel sans révéler la solution. Code:\n${Object.entries(files).map(([n,c])=>`---${n}---\n${c}`).join('\n')}`,'💡 J’ai besoin d’un indice.');window.requestNewLesson=()=>ask('Propose une micro-leçon et un défi adaptés à mon étape actuelle.','＋ Génère ma prochaine micro-leçon.');
window.autoFixCode=async()=>{const answer=await ask(`Corrige ce fichier ${active}. Retourne uniquement le code complet dans un bloc Markdown.\n${files[active]}`,'✨ Corrige le fichier actif.');const m=answer.match(/```(?:\w+)?\n([\s\S]*?)```/);if(m){files[active]=m[1].trim();switchFile(active);preview();save()}};
window.submitWorkToWolfy=async()=>{await ask(`Évalue ce projet sur 100. Indique clairement PASS si la note est au moins 70.\n${Object.entries(files).map(([n,c])=>`---${n}---\n${c}`).join('\n')}`,'🚀 Je soumets mon projet.');memory.xp+=25;memory.progress=Math.min(100,(memory.progress||0)+20);update();save();window.confetti?.({particleCount:70,spread:60})};
window.createNewFileModal=()=>{const name=prompt('Nom du fichier (ex. about.html)');if(!name||files[name])return;files[name]='';switchFile(name);save()};window.openModal=id=>document.getElementById(id).classList.add('open');window.closeModal=id=>document.getElementById(id).classList.remove('open');window.saveApiKeys=()=>{const r=$('#keyOpenRouter').value.trim(),o=$('#keyOpenAI').value.trim();if(r)localStorage.setItem('codewolf_key_openrouter',r);if(o)localStorage.setItem('codewolf_key_openai',o);closeModal('apiKeyModal')};
function update(){$('#userXp').textContent=$('#lbXp').textContent=memory.xp;$('#lbUsername').textContent=localStorage.getItem('codewolf_username')||'Toi';$('#progressLabel').textContent=(memory.progress||24)+'%';$('#progressBar').style.width=(memory.progress||24)+'%';for(let i=1;i<=4;i++){const el=$(`#curr_${i}`);el.className='path-item '+(i<memory.curriculumStep?'done':i===memory.curriculumStep?'active':'')}}
$('#activeFileTextarea').addEventListener('input',e=>{files[active]=e.target.value;preview();save()});$('#userInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMessage()}});addEventListener('message',e=>{if(e.data?.type==='cw-console')$('#consolePane').innerHTML+=`<br>&gt; ${String(e.data.message).replace(/[<>]/g,'')}`});async function hydrateCloud(){try{const cloud=await getCloudState();if(cloud?.profile){memory={...memory,level:cloud.profile.level,xp:cloud.profile.xp,curriculumStep:cloud.profile.curriculum_step,progress:cloud.profile.progress}}if(cloud?.project?.files&&Object.keys(cloud.project.files).length)files=cloud.project.files;renderFiles();if(!files[active])active=Object.keys(files)[0];switchFile(active);preview();update()}catch(e){console.warn('Mode hors ligne:',e.message)}}
renderFiles();switchFile(active);preview();update();hydrateCloud();