import {callWolfyAgent} from './aiClient.js';
import {loadCurriculum,loadLearningState,recommendNextSkill,lessonPrompt,lessonJsonSchema,validateLesson,saveLearningState} from './pedagogyEngine.js';
import {initializeCloudLearning,pullLearningState,saveGeneratedLesson,listMyLessons} from './pedagogyCloudClient.js';
import {streakStatus,todayKey} from './progressManager.js';
import {parseAiJson} from './jsonUtils.js';
import {saveLocalLesson} from './localLessonStore.js';
import {initProviderManager,saveProviderOrder} from './providerManager.js';
let memory={level:'Débutant',curriculumStep:1,progress:0,xp:120,goals:'Apprendre le développement web'};try{memory={...memory,...JSON.parse(localStorage.getItem('codewolf_student_memory')||'{}')}}catch{}
const $=s=>document.querySelector(s),name=localStorage.getItem('codewolf_ai_name')||localStorage.getItem('codewolf_username')||'développeur';
const progress=streakStatus();memory.xp=progress.xp;memory.streak=progress.streak;$('#studentName').textContent=$('#welcomeName').textContent=name;$('#studentLevel').textContent=memory.level;$('#userXp').textContent=progress.xp;$('#streakCount').textContent=progress.streak;$('#streakPlural').textContent=progress.streak===1?'':'s';$('#streakMessage').textContent=progress.lastLearningDay===todayKey()?'Objectif quotidien accompli !':'Termine une activité aujourd’hui !';$('#levelNumber').textContent=Math.max(1,Math.floor(memory.xp/250)+1);const done=progress.lastLearningDay===todayKey()?1:0;$('#dailyDone').textContent=done;$('#dailyBar').style.width=done?'100%':'0';
(async()=>{try{const cloud=await initializeCloudLearning();let state=loadLearningState();if(cloud.online){const remote=await pullLearningState();if(remote){state={...state,skills:{...state.skills,...remote.skills}};saveLearningState(state)}const lessons=await listMyLessons();const active=lessons.find(l=>l.status==='in_progress'||l.status==='generated');if(active){localStorage.setItem('codewolf_active_lesson',JSON.stringify({id:active.external_id,cloudId:active.id,skillId:active.skill_id,title:active.title,difficulty:active.difficulty,estimatedMinutes:active.estimated_minutes,xp:active.xp_reward,objectives:active.objectives,slides:active.slides,currentSlide:active.current_slide}));$('#recommendedTitle').textContent=active.title;$('#recommendedDescription').textContent='Reprends cette leçon là où tu l’as laissée.';document.querySelector('.lesson-type').textContent=`À REPRENDRE · ${active.estimated_minutes} MIN`;return}}const curriculum=await loadCurriculum(),skill=recommendNextSkill(curriculum,state,memory);$('#recommendedTitle').textContent=skill.title;$('#recommendedDescription').textContent=skill.objectives.join(' · ');document.querySelector('.lesson-type').textContent=`${skill.category.toUpperCase()} · NIVEAU ${skill.difficulty} · 15 MIN`}catch(e){console.warn('Cloud pédagogique indisponible, mode local:',e.message)}})();
const tourSteps=[{image:'/assets/characters/wolfy-front.svg',icon:'🐺',title:'Bienvenue dans ta meute',text:'Wolfy construit un parcours selon ton niveau. Chaque leçon, quiz et projet fait évoluer tes compétences.'},{icon:'▣',title:'Apprends avec des leçons vivantes',text:'Avance slide par slide, réponds aux questions et demande un indice lorsque tu bloques.'},{icon:'⌘',title:'Construis dans le Studio',text:'Les défis pratiques s’ouvrent dans un véritable espace de code avec aperçu et tests automatiques.'},{icon:'✦',title:'Progresse pour de vrai',text:'Les XP ne sont accordés qu’une fois par activité validée. Ta série augmente quand tu apprends chaque jour.'}];let tourIndex=0;function renderTour(){const s=tourSteps[tourIndex];$('#tourContent').innerHTML=`<div class="tour-icon">${s.image?`<img src="${s.image}" alt="Wolfy">`:s.icon}</div><small>ÉTAPE ${tourIndex+1} SUR ${tourSteps.length}</small><h2>${s.title}</h2><p>${s.text}</p>`;$('#tourDots').innerHTML=tourSteps.map((_,i)=>`<i class="${i===tourIndex?'active':''}"></i>`).join('');$('#tourNext').textContent=tourIndex===tourSteps.length-1?'Découvrir mon parcours →':'Suivant →'}function closeTour(){localStorage.setItem('codewolf_tour_done','1');$('#welcomeTour').classList.remove('open')}$('#tourNext').onclick=()=>{if(tourIndex<tourSteps.length-1){tourIndex++;renderTour()}else closeTour()};$('#tourSkip').onclick=closeTour;if(!localStorage.getItem('codewolf_tour_done')){$('#welcomeTour').classList.add('open');renderTour()}
const providerFields={openrouter:'#keyOpenRouter',mistral:'#keyMistral',gemini:'#keyGemini',anthropic:'#keyAnthropic',openai:'#keyOpenAI'};initProviderManager();window.openApiModal=()=>{for(const [p,id] of Object.entries(providerFields))$(id).value=localStorage.getItem(`codewolf_key_${p}`)||'';$('#apiKeyModal').classList.add('open')};window.closeApiModal=()=>$('#apiKeyModal').classList.remove('open');window.saveApiKeys=()=>{for(const [p,id] of Object.entries(providerFields)){const key=$(id).value.trim();if(key)localStorage.setItem(`codewolf_key_${p}`,key);else localStorage.removeItem(`codewolf_key_${p}`)}saveProviderOrder();closeApiModal()};
window.startFeatured=()=>{if(localStorage.getItem('codewolf_active_lesson'))location.href='/lesson';else window.generateLesson()};
let generationRunning=false,generationClock=null,generationStarted=0;
const generationPhases=[
 {at:0,stage:1,title:'Ok, je vais te cook ça !',message:'Je regarde ton niveau et je choisis la meilleure prochaine compétence.',label:'Analyse de ton parcours',progress:12},
 {at:6,stage:2,title:'Je construis ta leçon sur mesure.',message:'Je transforme la compétence en explications simples, exemples et slides.',label:'Création du contenu',progress:38},
 {at:16,stage:3,title:'Maintenant, je prépare les questions.',message:'Je crée des quiz adaptés — pas trop faciles, pas injustes non plus.',label:'Création des quiz',progress:62},
 {at:28,stage:4,title:'Dernière vérification de la recette…',message:'Je contrôle les réponses, le niveau et la cohérence du défi final.',label:'Validation pédagogique',progress:82},
 {at:45,stage:4,title:'Toujours là — le modèle réfléchit fort.',message:'Les modèles gratuits peuvent être plus lents. Ta demande est toujours en cours.',label:'Réponse du modèle en attente',progress:91}
];
function showGeneration(){generationRunning=true;generationStarted=Date.now();const box=$('#lessonGeneration');box.classList.add('open');box.setAttribute('aria-hidden','false');updateGeneration();generationClock=setInterval(updateGeneration,1000)}
function updateGeneration(){const seconds=Math.floor((Date.now()-generationStarted)/1000),phase=[...generationPhases].reverse().find(p=>seconds>=p.at)||generationPhases[0];setGenerationStage(phase.stage,phase);$('#generationTimer').textContent=`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`}
function setGenerationStage(stage,data={}){$('#generationTitle').textContent=data.title||$('#generationTitle').textContent;$('#generationMessage').textContent=data.message||$('#generationMessage').textContent;$('#generationStep').textContent=data.label||$('#generationStep').textContent;$('#generationBar').style.width=(data.progress||stage*22)+'%';for(let i=1;i<=4;i++){const el=$(`#genCheck${i}`);el.classList.toggle('active',i===stage);el.classList.toggle('done',i<stage)}}
function hideGeneration(){generationRunning=false;clearInterval(generationClock);const box=$('#lessonGeneration');box.classList.remove('open');box.setAttribute('aria-hidden','true')}
window.generateLesson=async()=>{
 if(generationRunning)return;
 if(!['openrouter','mistral','gemini','anthropic','openai'].some(p=>localStorage.getItem(`codewolf_key_${p}`))){window.openApiModal();return}
 const btn=document.activeElement,oldLabel=btn?.textContent;if(btn?.tagName==='BUTTON')btn.disabled=true;showGeneration();
 try{
  const curriculum=await loadCurriculum(),state=loadLearningState(),skill=recommendNextSkill(curriculum,state,memory);state.currentSkill=skill.id;saveLearningState(state);setGenerationStage(2,{title:`Je te prépare « ${skill.title} ».`,message:'Chaque explication est adaptée à ta progression actuelle.',label:'Création du contenu',progress:30});
  let lesson=null,errors=[];const requestLesson=correction=>callWolfyAgent([{role:'user',content:lessonPrompt(skill,state,memory)+correction}],memory,'free',10,'fr',{json:true,schema:lessonJsonSchema(skill.id),schemaName:'codewolf_lesson'});
  setGenerationStage(2,{title:'Je prépare deux recettes en parallèle.',message:'Je garderai la version la plus claire et la plus fiable.',label:'Double génération',progress:38});
  const firstWave=await Promise.allSettled([requestLesson('\nCrée la version A, très visuelle et progressive.'),requestLesson('\nCrée la version B, très concrète et interactive.')]);
  for(const result of firstWave){if(result.status!=='fulfilled'){errors.push(result.reason?.message||'Modèle indisponible');continue}try{const candidate=parseAiJson(result.value),check=validateLesson(candidate,skill);if(check.ok){lesson=candidate;break}errors.push(...check.errors)}catch(e){errors.push(e.message||'JSON invalide')}}
  if(!lesson){setGenerationStage(4,{title:'Je répare la meilleure tentative.',message:'Je corrige automatiquement les contraintes non respectées.',label:'Validation renforcée',progress:88});const unique=[...new Set(errors)].slice(0,8),answer=await requestLesson(`\nCorrige impérativement ces erreurs observées: ${unique.join('; ')}.`);const candidate=parseAiJson(answer),check=validateLesson(candidate,skill);if(check.ok)lesson=candidate;else errors=check.errors}
  if(!lesson)throw Error(errors.join(', '));setGenerationStage(4,{title:'C’est prêt !',message:'La leçon est valide. Je l’ajoute à ta bibliothèque.',label:'Sauvegarde de la leçon',progress:100});
  try{lesson.cloudId=await saveGeneratedLesson(lesson,'BYOK')}catch(e){console.warn('Leçon sauvegardée localement:',e.message)}
  saveLocalLesson(lesson,'generated');localStorage.setItem('codewolf_active_lesson',JSON.stringify(lesson));setTimeout(()=>location.href='/lesson',450)
 }catch(e){hideGeneration();alert(`Wolfy n’a pas pu produire une leçon conforme : ${e.message}`);if(btn?.tagName==='BUTTON'){btn.disabled=false;btn.textContent=oldLabel||'✨ Générer une leçon'}}
};
function defaultLesson(){return {title:'Les fondations d’une page web',topic:'HTML',duration:15,xp:80,slides:[{type:'concept',title:'Le langage du navigateur',content:'HTML décrit la **structure** d’une page. Chaque élément donne du sens au contenu.'},{type:'example',title:'Une structure claire',content:'Les balises s’imbriquent comme des boîtes.',code:'<main>\n  <h1>Mon projet</h1>\n  <p>Bienvenue !</p>\n</main>'},{type:'quiz',title:'Question éclair',content:'Quelle balise contient le contenu principal ?',question:'Choisis la meilleure réponse.',choices:['<main>','<style>','<meta>'],answer:0,hint:'Elle porte le même nom que son rôle en anglais.'},{type:'concept',title:'La sémantique',content:'Utilise `<header>`, `<nav>`, `<main>` et `<footer>` plutôt que des `<div>` partout. Ton code devient accessible et lisible.'},{type:'quiz',title:'À toi de décider',question:'Quelle balise convient à une navigation ?',choices:['<section>','<nav>','<aside>'],answer:1,hint:'Son nom est une abréviation directe.'},{type:'challenge',title:'Mission pratique',content:'Crée dans le studio une carte avec un `<article>`, un titre, un paragraphe et un bouton.',code:'<!-- À toi de construire -->'}]}}