import {loadLearningState,recordQuiz,saveLearningState,nextReviewDate,loadCurriculum,allSkills,lessonPrompt,lessonJsonSchema,validateLesson} from './pedagogyEngine.js';
import {startLessonAttempt,saveQuizAnswer,updateLessonProgress,completeCloudLesson,pushSkillState,saveGeneratedLesson} from './pedagogyCloudClient.js';
import {awardXp,registerLearningDay} from './progressManager.js';
import {updateLocalLesson,saveLocalLesson} from './localLessonStore.js';
import {parseAiJson} from './jsonUtils.js';
const $=s=>document.querySelector(s);let lesson;try{lesson=JSON.parse(localStorage.getItem('codewolf_active_lesson'))}catch{}if(!lesson?.slides?.length)location.href='/dashboard';
let index=Math.min(Number(lesson.currentSlide||0),lesson.slides.length-1),answered=false,attemptId=null,quizCorrect=0,quizTotal=0,slideStartedAt=Date.now();
if(!lesson.reviewMode){updateLocalLesson(lesson,{status:'in_progress',current_slide:index});startLessonAttempt(lesson).then(id=>attemptId=id).catch(e=>console.warn('Tentative locale:',e.message))}
$('#lessonTitle').textContent=lesson.title;$('#lessonXp').textContent=lesson.xp||80;
const labels={hook:'AVANT DE COMMENCER',concept:'À RETENIR',analogy:'IMAGE MENTALE',example:'EXEMPLE',prediction:'PRÉDIS LE RÉSULTAT',quiz:'QUESTION',true_false:'VRAI OU FAUX',matching:'ASSOCIATION',ordering:'REMETS DANS L’ORDRE',spot_error:'REPÈRE L’ERREUR',guided_practice:'À TOI, AVEC DE L’AIDE',reflection:'AVEC TES MOTS',recap:'RÉCAPITULATIF',challenge:'MISSION'};let preloadStarted=false;
async function preloadNextLesson(){if(preloadStarted||lesson.reviewMode||!window.Worker)return;const key=localStorage.getItem('codewolf_key_openrouter');if(!key)return;const marker=`codewolf_prefetch:${lesson.id}`;if(localStorage.getItem(marker))return;preloadStarted=true;localStorage.setItem(marker,'running');try{const curriculum=await loadCurriculum(),skill=allSkills(curriculum).find(s=>s.id===lesson.skillId);if(!skill)throw Error('Compétence inconnue');let profile={};try{profile=JSON.parse(localStorage.getItem('codewolf_student_memory')||'{}')}catch{}const state=loadLearningState(),prompt=lessonPrompt(skill,state,profile)+'\nCrée une leçon de consolidation différente de la leçon actuelle, avec de nouveaux exemples et un nouveau titre.';const worker=new Worker('/js/lessonPreloader.worker.js',{type:'module'}),jobId=crypto.randomUUID();const result=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>{worker.terminate();reject(Error('Préchargement trop long'))},95000);worker.onmessage=e=>{if(e.data.jobId!==jobId)return;clearTimeout(timer);worker.terminate();e.data.ok?resolve(e.data):reject(Error(e.data.error))};worker.postMessage({key,prompt,schema:lessonJsonSchema(skill.id),jobId})});const candidate=parseAiJson(result.content),check=validateLesson(candidate,skill);if(!check.ok)throw Error(check.errors.join(', '));try{candidate.cloudId=await saveGeneratedLesson(candidate,result.model||'openrouter/free')}catch{}saveLocalLesson(candidate,'generated');localStorage.setItem(marker,'done')}catch(e){console.info('Préchargement reporté:',e.message);localStorage.removeItem(marker)}}
function render(){answered=false;slideStartedAt=Date.now();const s=lesson.slides[index],total=lesson.slides.length;if(index>=Math.floor(total/2))preloadNextLesson();$('#slideCount').textContent=`${index+1} / ${total}`;$('#lessonProgress').style.width=`${(index+1)/total*100}%`;$('#slideKind').textContent=labels[s.type]||s.type.toUpperCase();$('#slideTitle').textContent=s.title||'';const markdown=String(s.content||s.question||'').replace(/\\n/g,'\n');$('#slideContent').innerHTML=DOMPurify.sanitize(marked.parse(markdown,{breaks:true,gfm:true}));const pre=$('#codeBlock');pre.hidden=!s.code;pre.querySelector('code').textContent=s.code||'';const area=$('#quizArea');area.innerHTML='';$('#feedback').hidden=true;const hintAllowed=s.type==='quiz'||s.type==='prediction'||s.type==='spot_error'||(s.type==='challenge'&&s.mode!=='concept');$('#hintBtn').hidden=!s.hint||!hintAllowed;$('#nextBtn').disabled=false;$('#nextBtn').textContent=index===total-1?'Terminer la leçon ✓':'Continuer →';
 if(['quiz','prediction','true_false','spot_error'].includes(s.type)){renderChoices(s,area);$('#nextBtn').disabled=true}
 if(s.type==='matching'){renderMatching(s,area);$('#nextBtn').disabled=true}
 if(s.type==='ordering'){renderOrdering(s,area);$('#nextBtn').disabled=true}
 if(s.type==='reflection'){renderReflection(s,area);$('#nextBtn').disabled=true}
 if(s.type==='guided_practice'&&s.starter){const box=document.createElement('div');box.className='guided-starter';box.innerHTML='<small>CODE DE DÉPART</small>';for(const [name,code] of Object.entries(s.starter)){const title=document.createElement('b');title.textContent=name;const p=document.createElement('pre');p.textContent=code;box.append(title,p)}area.append(box)}
 if(s.type==='challenge'){$('#nextBtn').textContent=s.mode==='concept'?'Terminer cette introduction ✓':'Ouvrir le Studio →';$('#wolfTip').textContent=s.mode==='concept'?'Explique-le simplement, comme à un ami.':'C’est en construisant qu’on apprend.'}else $('#wolfTip').textContent=['quiz','prediction','spot_error'].includes(s.type)?'Prends quelques secondes pour raisonner.':'Une idée à la fois.'
}
function renderChoices(s,area){(s.choices||[]).forEach((choice,i)=>{const b=document.createElement('button');b.className='quiz-choice';b.innerHTML=DOMPurify.sanitize(`<span>${String.fromCharCode(65+i)}</span>${choice}`);b.onclick=()=>answerChoice(s,i,b);area.append(b)})}
function answerChoice(s,i,button){if(answered)return;answered=true;const ok=i===Number(s.answer);recordResult(s,ok,i);areaButtons().forEach((b,n)=>{b.disabled=true;if(n===Number(s.answer))b.classList.add('correct')});if(!ok)button.classList.add('wrong');showFeedback(s,ok);$('#nextBtn').disabled=false}
function areaButtons(){return [...document.querySelectorAll('#quizArea .quiz-choice')]}
function recordResult(s,ok,selected){const learning=recordQuiz(loadLearningState(),lesson.skillId,ok),skill=learning.skills[lesson.skillId];quizTotal++;if(ok)quizCorrect++;if(!ok&&s.misconception){skill.commonErrors=[...new Set([`${s.misconception}: ${s.title}`,...(skill.commonErrors||[])])].slice(0,5)}Object.assign(skill,nextReviewDate({correct:ok,confidence:ok?'normal':'low'}));saveLearningState(learning);pushSkillState(lesson.skillId,learning).catch(()=>{});saveQuizAnswer({lesson,attemptId,slideIndex:index,question:s.question||s.title,selected,correct:Number(s.answer||0),isCorrect:ok,responseTimeMs:Date.now()-slideStartedAt}).catch(()=>{})}
function showFeedback(s,ok){const f=$('#feedback');f.hidden=false;f.className='answer-feedback '+(ok?'good':'bad');const intro=ok?'✓ Bien vu !':'Pas encore — c’est une confusion utile à repérer.';f.innerHTML=DOMPurify.sanitize(marked.parse(`${intro}\n\n${s.explanation||(!ok?'Observe la réponse mise en évidence et compare-la à ton raisonnement.':'Tu peux continuer.')}`,{breaks:true}))}
function renderMatching(s,area){const pairs=s.pairs||[],rights=[...pairs.map(p=>p.right)].sort(()=>Math.random()-.5),box=document.createElement('div');box.className='matching-grid';pairs.forEach((pair,i)=>{const row=document.createElement('label');row.innerHTML=`<span>${pair.left}</span>`;const select=document.createElement('select');select.innerHTML=DOMPurify.sanitize('<option value="">Choisir…</option>'+rights.map(v=>`<option>${v}</option>`).join(''));select.onchange=()=>{if([...box.querySelectorAll('select')].every(x=>x.value))checkMatching(s,box)};row.append(select);box.append(row)});area.append(box)}
function checkMatching(s,box){if(answered)return;answered=true;const selects=[...box.querySelectorAll('select')],ok=selects.every((x,i)=>x.value===s.pairs[i].right);selects.forEach((x,i)=>x.classList.add(x.value===s.pairs[i].right?'correct':'wrong'));recordResult(s,ok,ok?0:1);showFeedback(s,ok);$('#nextBtn').disabled=false}
function renderOrdering(s,area){const correct=s.items||[],current=[...correct].sort(()=>Math.random()-.5),box=document.createElement('div');box.className='ordering-list';function draw(){box.innerHTML='';current.forEach((item,i)=>{const row=document.createElement('div');row.innerHTML=`<span>${i+1}</span><b></b><div><button ${i===0?'disabled':''}>↑</button><button ${i===current.length-1?'disabled':''}>↓</button></div>`;row.querySelector('b').textContent=item;const [up,down]=row.querySelectorAll('button');up.onclick=()=>{[current[i-1],current[i]]=[current[i],current[i-1]];draw()};down.onclick=()=>{[current[i+1],current[i]]=[current[i],current[i+1]];draw()};box.append(row)});const verify=document.createElement('button');verify.className='btn btn-primary';verify.textContent='Vérifier l’ordre';verify.onclick=()=>{if(answered)return;answered=true;const ok=current.every((v,i)=>v===correct[i]);recordResult(s,ok,ok?0:1);showFeedback(s,ok);$('#nextBtn').disabled=false};box.append(verify)}draw();area.append(box)}
function renderReflection(s,area){const textarea=document.createElement('textarea');textarea.className='reflection-input';textarea.placeholder='Explique avec tes propres mots…';const count=document.createElement('small');count.textContent='10 caractères minimum';textarea.oninput=()=>{$('#nextBtn').disabled=textarea.value.trim().length<10;count.textContent=`${textarea.value.trim().length} caractères`};area.append(textarea,count)}
$('#hintBtn').onclick=()=>{const s=lesson.slides[index],f=$('#feedback');f.hidden=false;f.className='answer-feedback';f.textContent='💡 '+s.hint};
$('#nextBtn').onclick=()=>{const s=lesson.slides[index];if(s.type==='challenge'&&s.mode!=='concept'){localStorage.setItem('codewolf_current_challenge',JSON.stringify({...s,skillId:lesson.skillId,lessonId:lesson.id,lessonCloudId:lesson.cloudId||null}));if(s.starter)localStorage.setItem('codewolf_workspace',JSON.stringify(s.starter));location.href='/studio';return}if(index<lesson.slides.length-1){index++;lesson.currentSlide=index;localStorage.setItem('codewolf_active_lesson',JSON.stringify(lesson));updateLocalLesson(lesson,{status:'in_progress',current_slide:index});updateLessonProgress(lesson,attemptId,index).catch(()=>{});render()}else complete()};
function complete(){if(!lesson.reviewMode)completeCloudLesson(lesson,attemptId,quizCorrect,quizTotal).catch(()=>{});let memory={xp:120,progress:0};try{memory={...memory,...JSON.parse(localStorage.getItem('codewolf_student_memory')||'{}')}}catch{}const reward=lesson.reviewMode?{progress:{xp:memory.xp},awarded:false}:awardXp(lesson.xp||80,`lesson:${lesson.cloudId||lesson.id}`);if(!lesson.reviewMode)registerLearningDay();memory.xp=reward.progress.xp;memory.progress=Math.min(100,(memory.progress||0)+(reward.awarded?20:0));if(memory.onboardingConceptsPending)memory.onboardingConceptsPending=false;localStorage.setItem('codewolf_student_memory',JSON.stringify(memory));if(!lesson.reviewMode)updateLocalLesson(lesson,{status:'completed',current_slide:lesson.slides.length-1,completed_at:new Date().toISOString()});localStorage.removeItem('codewolf_active_lesson');confetti?.({particleCount:140,spread:85,origin:{y:.65}});$('.slide-card').innerHTML=`<div class="lesson-complete"><img src="/assets/wolfy.svg"><span class="eyebrow">LEÇON TERMINÉE</span><h1>Excellent travail !</h1><p>${lesson.reviewMode?'Révision terminée — aucun XP supplémentaire.':`Tu gagnes <strong>+${lesson.xp||80} XP</strong>. Wolfy adaptera la suite à tes réponses.`}</p><button class="btn btn-primary btn-lg" onclick="location.href='/dashboard'">Retour à mes leçons →</button></div>`}
render();