import {listMyLessons,initializeCloudLearning} from './pedagogyCloudClient.js';import {loadCurriculum,allSkills,loadLearningState,recommendNextSkill} from './pedagogyEngine.js';import {streakStatus} from './progressManager.js';
const $=s=>document.querySelector(s);let lessons=[],skills=[],state=loadLearningState(),filter='all',search='';$('#libraryXp').textContent=streakStatus().xp;
async function init(){try{const curriculum=await loadCurriculum();skills=allSkills(curriculum);await initializeCloudLearning();lessons=await listMyLessons(100)}catch(e){console.warn('Bibliothèque locale:',e.message)}const local=readLocalLesson();if(local&&!lessons.some(l=>l.id===local.id||l.external_id===local.external_id))lessons.unshift(local);renderAll()}
function readLocalLesson(){try{const l=JSON.parse(localStorage.getItem('codewolf_active_lesson'));if(!l)return null;return {id:l.cloudId||l.id,external_id:l.id,skill_id:l.skillId,title:l.title,difficulty:l.difficulty,estimated_minutes:l.estimatedMinutes,xp_reward:l.xp,objectives:l.objectives,slides:l.slides,status:'in_progress',current_slide:l.currentSlide||0,local:true}}catch{return null}}
function skill(id){return skills.find(s=>s.id===id)||{id,title:id||'Développement web',category:'Code',difficulty:1,objectives:[]}}
function percent(l){return Math.round(((l.current_slide||0)+1)/Math.max(1,l.slides?.length||1)*100)}
function icon(category){return {HTML:'<>',CSS:'#',JavaScript:'JS',Accessibilité:'A11Y',Qualité:'✓'}[category]||'</>'}
function openLesson(l,review=false){const payload={id:l.external_id||l.id,cloudId:l.local?null:l.id,skillId:l.skill_id,title:l.title,difficulty:l.difficulty,estimatedMinutes:l.estimated_minutes,xp:l.xp_reward,objectives:l.objectives||[],slides:l.slides||[],currentSlide:review?0:(l.current_slide||0),reviewMode:review};localStorage.setItem('codewolf_active_lesson',JSON.stringify(payload));location.href='/lesson'}
function card(l){const s=skill(l.skill_id),done=l.status==='completed',p=done?100:percent(l);const article=document.createElement('article');article.className='library-card';article.dataset.category=s.category;article.innerHTML=`<div class="library-card-top"><span class="subject-icon ${s.category.toLowerCase()}">${icon(s.category)}</span><span class="lesson-status ${done?'done':''}">${done?'✓ Terminée':l.status==='in_progress'?'● En cours':'○ À commencer'}</span></div><small>${s.category.toUpperCase()} · NIVEAU ${l.difficulty||s.difficulty}</small><h3>${escapeHtml(l.title)}</h3><p>${escapeHtml((l.objectives||s.objectives||[]).slice(0,2).join(' · ')||'Une leçon personnalisée par Wolfy.')}</p><div class="card-progress"><div><i style="width:${p}%"></i></div><span>${p}%</span></div><footer><span>◷ ${l.estimated_minutes||15} min</span><span>✦ ${l.xp_reward||0} XP</span><button>${done?'Revoir':'Continuer'} →</button></footer>`;article.querySelector('button').onclick=()=>openLesson(l,done);return article}
function renderAll(){const completed=lessons.filter(l=>l.status==='completed'),progress=lessons.filter(l=>l.status==='in_progress'||l.status==='generated');$('#statCompleted').textContent=completed.length;$('#statProgress').textContent=progress.length;$('#statMastered').textContent=Object.values(state.skills||{}).filter(s=>s.mastery>=80).length;const cg=$('#continueGrid');cg.innerHTML='';progress.slice(0,2).forEach(l=>cg.append(continueCard(l)));$('#continueSection').hidden=!progress.length;renderRecommendations();renderLibrary()}
function continueCard(l){const s=skill(l.skill_id),p=percent(l),el=document.createElement('article');el.className='continue-card';el.innerHTML=`<div class="continue-art"><span>${icon(s.category)}</span></div><div><small>${s.category} · ${p}% TERMINÉ</small><h3>${escapeHtml(l.title)}</h3><p>${Math.min((l.current_slide||0)+1,l.slides?.length||1)} slides sur ${l.slides?.length||1}</p><div class="progress"><i style="width:${p}%"></i></div><button class="btn btn-primary btn-sm">Reprendre →</button></div>`;el.querySelector('button').onclick=()=>openLesson(l);return el}
function renderRecommendations(){const box=$('#recommendGrid');box.innerHTML='';if(!skills.length)return;const first=recommendNextSkill({tracks:[{levels:[{skills}]}]},state,{}),ordered=[first,...skills.filter(s=>s.id!==first.id&&((s.prerequisites||[]).every(id=>(state.skills[id]?.mastery||0)>=55)))].slice(0,3);ordered.forEach((s,i)=>{const mastery=state.skills[s.id]?.mastery||0,el=document.createElement('article');el.className='recommend-card';el.innerHTML=`<span class="subject-icon">${icon(s.category)}</span><div><small>${i===0?'RECOMMANDÉ':'PROCHAINE COMPÉTENCE'} · ${s.category}</small><h3>${s.title}</h3><p>${s.objectives.join(' · ')}</p><span class="mastery-chip">Maîtrise actuelle : ${mastery}%</span></div>`;box.append(el)})}
function renderLibrary(){const grid=$('#lessonLibraryGrid');grid.innerHTML='';const shown=lessons.filter(l=>{const s=skill(l.skill_id),text=(l.title+' '+s.title+' '+s.category).toLowerCase(),matchesSearch=text.includes(search);let matches=filter==='all'||filter===s.category||filter==='completed'&&l.status==='completed'||filter==='review'&&(state.skills[l.skill_id]?.attempts>0&&state.skills[l.skill_id]?.mastery<55);return matchesSearch&&matches});shown.forEach(l=>grid.append(card(l)));$('#resultCount').textContent=`${shown.length} leçon${shown.length===1?'':'s'}`;$('#emptyLibrary').hidden=shown.length>0}
$('#lessonSearch').oninput=e=>{search=e.target.value.trim().toLowerCase();renderLibrary()};$('#filterRow').onclick=e=>{const b=e.target.closest('button');if(!b)return;$('#filterRow').querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;renderLibrary()};$('#generateRecommended').onclick=()=>location.href='/dashboard';function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}window.openLesson=openLesson;init();