let curriculumCache;
export async function loadCurriculum(){if(curriculumCache)return curriculumCache;const r=await fetch('/data/curriculum.json');if(!r.ok)throw Error('Programme indisponible');curriculumCache=await r.json();return curriculumCache}
export function allSkills(curriculum){return curriculum.tracks.flatMap(t=>t.levels.flatMap(l=>l.skills.map(s=>({...s,level:l.id,track:t.id}))))}
export function createLearningState(existing={}){return {version:1,skills:{},lessonHistory:[],currentSkill:null,...existing}}
export function skillState(state,id){return state.skills[id]||{mastery:0,attempts:0,quizCorrect:0,quizTotal:0,challengesPassed:0,commonErrors:[],lastPracticedAt:null}}
export function prerequisitesMet(skill,state){return (skill.prerequisites||[]).every(id=>skillState(state,id).mastery>=55)}
export function recommendNextSkill(curriculum,state,profile={}){const skills=allSkills(curriculum),available=skills.filter(s=>prerequisitesMet(s,state));const unmastered=available.filter(s=>skillState(state,s.id).mastery<80);if(!unmastered.length)return skills.find(s=>skillState(state,s.id).mastery<100)||skills[0];return unmastered.sort((a,b)=>{const sa=skillState(state,a.id),sb=skillState(state,b.id);const reviewA=sa.attempts&&sa.mastery<55?-25:0,reviewB=sb.attempts&&sb.mastery<55?-25:0;return (a.difficulty*10+sa.mastery+reviewA)-(b.difficulty*10+sb.mastery+reviewB)})[0]}
export function validateLesson(input,expectedSkill){const errors=[];if(!input||typeof input!=='object')return {ok:false,errors:['Réponse non structurée']};if(typeof input.title!=='string'||input.title.length<5)errors.push('Titre absent');if(input.skillId!==expectedSkill.id)errors.push('Compétence incorrecte');if(!Array.isArray(input.objectives)||input.objectives.length<1)errors.push('Objectifs absents');if(!Number.isFinite(Number(input.estimatedMinutes)))errors.push('Durée invalide');if(!Array.isArray(input.slides)||input.slides.length<7||input.slides.length>12)errors.push('La leçon doit avoir 7 à 12 slides');const allowed=['hook','concept','analogy','example','prediction','quiz','true_false','matching','ordering','spot_error','guided_practice','reflection','recap','challenge'];let quiz=0,challenge=0;(input.slides||[]).forEach((s,i)=>{if(!allowed.includes(s.type))errors.push(`Slide ${i+1}: type invalide`);if(!s.title||(!(s.content||s.question)))errors.push(`Slide ${i+1}: contenu absent`);if(['quiz','prediction','true_false','spot_error'].includes(s.type)){quiz++;if(!Array.isArray(s.choices)||s.choices.length<2||!Number.isInteger(s.answer)||s.answer<0||s.answer>=s.choices.length)errors.push(`Interaction ${i+1}: réponses invalides`)}if(s.type==='ordering'&&(!Array.isArray(s.items)||s.items.length<3))errors.push(`Ordre ${i+1}: éléments insuffisants`);if(s.type==='matching'&&(!Array.isArray(s.pairs)||s.pairs.length<2))errors.push(`Association ${i+1}: paires insuffisantes`);if(s.type==='challenge'){challenge++;if(s.mode!=='concept'&&(!Array.isArray(s.tests)||s.tests.length<2))errors.push('Le défi pratique doit inclure au moins 2 tests')}});if(quiz<2)errors.push('Au moins 2 quiz requis');if(challenge!==1)errors.push('Un unique défi est requis');if(input.slides?.at(-1)?.type!=='challenge')errors.push('Le défi doit terminer la leçon');return {ok:errors.length===0,errors}}
export function recordQuiz(state,skillId,correct){const s={...skillState(state,skillId)};s.attempts++;s.quizTotal++;if(correct)s.quizCorrect++;const accuracy=s.quizTotal?s.quizCorrect/s.quizTotal:0;s.mastery=Math.max(0,Math.min(100,Math.round(s.mastery*.72+accuracy*100*.28)));s.lastPracticedAt=new Date().toISOString();state.skills[skillId]=s;return state}
export function recordChallenge(state,skillId,{passed,score=0,errors=[]}){const s={...skillState(state,skillId)};s.attempts++;if(passed)s.challengesPassed++;s.mastery=Math.max(0,Math.min(100,Math.round(s.mastery*.55+score*.45)));s.commonErrors=[...new Set([...errors,...s.commonErrors])].slice(0,5);s.lastPracticedAt=new Date().toISOString();state.skills[skillId]=s;return state}
export function lessonPrompt(skill,state,profile){const status=skillState(state,skill.id),absoluteBeginner=profile?.onboardingConceptsPending||/début/i.test(profile?.level||'');return `Tu es l’ingénieur pédagogique de CodeWolf. Crée une leçon active en français sur ${JSON.stringify(skill)}. Profil: ${JSON.stringify(profile)}. Maîtrise: ${JSON.stringify(status)}. Donne un titre court et original, différent du nom officiel de la compétence. Principes obligatoires: une seule idée par slide; phrases courtes; analogie concrète; exemples exacts; feedback explicatif; aucune notion hors prérequis. Séquence: 1 hook qui active les connaissances sans noter; 1 concept; 1 analogie; 1 vérification immédiate (prediction, true_false, quiz ou spot_error); 1 example guidé; 1 seconde interaction; 1 guided_practice; 1 reflection ou recap; puis exactement 1 challenge final. Utilise 7 à 12 slides. Varie les interactions parmi prediction, quiz, true_false, matching, ordering et spot_error. Pour chaque question à choix, fournis choices, answer, hint, explanation et misconception parmi vocabulary, concept, syntax, logic, prerequisite, attention. Pour ordering, fournis items déjà dans le bon ordre; l’interface les mélangera. Pour matching, fournis pairs avec left/right. Pour guided_practice, fournis un starter partiel. ${absoluteBeginner&&skill.id==='html.document'?'Cette personne part de zéro: explique Internet, navigateur, frontend/backend, puis HTML/CSS/JavaScript avant tout code. Challenge final mode concept, sans tests.':'Challenge final mode code avec starter HTML5 complet et 2 à 5 tests contains, notContains ou regex.'} Réponds uniquement selon le schéma JSON fourni.`}
export function lessonJsonSchema(skillId){return {type:'object',additionalProperties:false,required:['id','skillId','title','difficulty','objectives','estimatedMinutes','xp','slides'],properties:{id:{type:'string'},skillId:{type:'string',const:skillId},title:{type:'string'},difficulty:{type:'integer',minimum:1,maximum:5},objectives:{type:'array',minItems:1,items:{type:'string'}},estimatedMinutes:{type:'integer',minimum:5,maximum:60},xp:{type:'integer',minimum:0,maximum:300},slides:{type:'array',minItems:7,maxItems:12,items:{type:'object',additionalProperties:false,required:['type','title','content'],properties:{type:{type:'string',enum:['hook','concept','analogy','example','prediction','quiz','true_false','matching','ordering','spot_error','guided_practice','reflection','recap','challenge']},title:{type:'string'},content:{type:'string'},code:{type:['string','null']},question:{type:['string','null']},choices:{type:['array','null'],items:{type:'string'}},answer:{type:['integer','null']},hint:{type:['string','null']},explanation:{type:['string','null']},misconception:{type:['string','null'],enum:['vocabulary','concept','syntax','logic','prerequisite','attention',null]},mode:{type:['string','null'],enum:['code','concept',null]},items:{type:['array','null'],items:{type:'string'}},pairs:{type:['array','null'],items:{type:'object',additionalProperties:false,required:['left','right'],properties:{left:{type:'string'},right:{type:'string'}}}},starter:{type:['object','null'],additionalProperties:{type:'string'}},tests:{type:['array','null'],items:{type:'object',additionalProperties:false,required:['type','file','value'],properties:{type:{type:'string',enum:['contains','notContains','regex']},file:{type:'string',enum:['index.html','style.css','script.js']},value:{type:'string'},label:{type:['string','null']}}}}}}}}}}
export function masteryBand(value=0){if(value<20)return {id:'undiscovered',label:'Non découvert'};if(value<40)return {id:'discovering',label:'Découverte'};if(value<60)return {id:'understanding',label:'Compréhension'};if(value<80)return {id:'applying',label:'Application'};return {id:'mastered',label:'Maîtrise'}}
export function nextReviewDate({correct=false,confidence='normal',challengeFailed=false}={}){const days=challengeFailed?0:!correct?1:confidence==='low'?3:7;const date=new Date();date.setDate(date.getDate()+days);return {nextReviewAt:date.toISOString(),reviewIntervalDays:days}}
export function saveLearningState(state){localStorage.setItem('codewolf_learning_state',JSON.stringify(state))}
export function loadLearningState(){try{return createLearningState(JSON.parse(localStorage.getItem('codewolf_learning_state')||'{}'))}catch{return createLearningState()}}
