import {supabase} from './auth.js';
async function user(){if(!supabase)return null;const {data,error}=await supabase.auth.getUser();if(error)return null;return data.user}
export async function initializeCloudLearning(){const u=await user();if(!u)return {online:false};const {error}=await supabase.rpc('initialize_my_skills');if(error)throw error;return {online:true,user:u}}
export async function pullLearningState(){const u=await user();if(!u)return null;const {data,error}=await supabase.from('user_skills').select('skill_id,mastery,attempts,quiz_correct,quiz_total,challenges_passed,common_errors,last_practiced_at').eq('user_id',u.id);if(error)throw error;const skills={};for(const row of data||[])skills[row.skill_id]={mastery:row.mastery,attempts:row.attempts,quizCorrect:row.quiz_correct,quizTotal:row.quiz_total,challengesPassed:row.challenges_passed,commonErrors:row.common_errors||[],lastPracticedAt:row.last_practiced_at};return {version:1,skills}}
export async function pushSkillState(skillId,state){const u=await user();if(!u)return;const s=state.skills?.[skillId];if(!s)return;const {error}=await supabase.from('user_skills').upsert({user_id:u.id,skill_id:skillId,mastery:s.mastery||0,attempts:s.attempts||0,quiz_correct:s.quizCorrect||0,quiz_total:s.quizTotal||0,challenges_passed:s.challengesPassed||0,common_errors:s.commonErrors||[],last_practiced_at:s.lastPracticedAt},{onConflict:'user_id,skill_id'});if(error)throw error}
export async function saveGeneratedLesson(lesson,model='BYOK'){const u=await user();if(!u)return null;const payload={owner_id:u.id,skill_id:lesson.skillId,external_id:lesson.id||crypto.randomUUID(),title:lesson.title,difficulty:lesson.difficulty||1,estimated_minutes:lesson.estimatedMinutes||15,xp_reward:lesson.xp||0,objectives:lesson.objectives||[],slides:lesson.slides||[],generation_model:model,status:'generated'};const {data,error}=await supabase.from('lessons').insert(payload).select('id').single();if(error)throw error;return data.id}
export async function startLessonAttempt(lesson){const u=await user();if(!u||!lesson.cloudId)return null;await supabase.from('lessons').update({status:'in_progress',started_at:new Date().toISOString()}).eq('id',lesson.cloudId).eq('owner_id',u.id);const {count}=await supabase.from('lesson_attempts').select('*',{count:'exact',head:true}).eq('lesson_id',lesson.cloudId);const {data,error}=await supabase.from('lesson_attempts').insert({owner_id:u.id,lesson_id:lesson.cloudId,attempt_number:(count||0)+1,status:'in_progress'}).select('id').single();if(error)throw error;return data.id}
export async function saveQuizAnswer({lesson,attemptId,slideIndex,question,selected,correct,isCorrect,responseTimeMs}){const u=await user();if(!u||!lesson.cloudId||!attemptId)return;const {error}=await supabase.from('quiz_answers').upsert({owner_id:u.id,lesson_id:lesson.cloudId,attempt_id:attemptId,skill_id:lesson.skillId,slide_index:slideIndex,question,selected_answer:selected,correct_answer:correct,is_correct:isCorrect,response_time_ms:responseTimeMs},{onConflict:'attempt_id,slide_index'});if(error)throw error;await logLearningEvent('quiz_answered',{skillId:lesson.skillId,lessonId:lesson.cloudId,metadata:{correct:isCorrect,slideIndex}})}
export async function updateLessonProgress(lesson,attemptId,currentSlide){const u=await user();if(!u||!lesson.cloudId)return;await Promise.all([supabase.from('lessons').update({current_slide:currentSlide,status:'in_progress'}).eq('id',lesson.cloudId).eq('owner_id',u.id),attemptId?supabase.from('lesson_attempts').update({current_slide:currentSlide}).eq('id',attemptId).eq('owner_id',u.id):Promise.resolve()])}
export async function completeCloudLesson(lesson,attemptId,quizCorrect,quizTotal){const u=await user();if(!u||!lesson.cloudId)return;const now=new Date().toISOString();await Promise.all([supabase.from('lessons').update({status:'completed',completed_at:now,current_slide:lesson.slides.length-1}).eq('id',lesson.cloudId).eq('owner_id',u.id),attemptId?supabase.from('lesson_attempts').update({status:'completed',completed_at:now,quiz_correct:quizCorrect,quiz_total:quizTotal,score:quizTotal?Math.round(quizCorrect/quizTotal*100):100,xp_awarded:lesson.xp||0}).eq('id',attemptId).eq('owner_id',u.id):Promise.resolve(),logLearningEvent('lesson_completed',{skillId:lesson.skillId,lessonId:lesson.cloudId,metadata:{xp:lesson.xp||0}})])}
export async function saveChallengeAttempt({challenge,files,tests,automaticScore,aiScore,finalScore,passed,feedback}){const u=await user();if(!u||!challenge?.skillId)return;const errors=tests.filter(t=>!t.passed).map(t=>t.label);const {error}=await supabase.from('challenge_attempts').insert({owner_id:u.id,lesson_id:challenge.lessonCloudId||null,skill_id:challenge.skillId,challenge_title:challenge.title||'Défi CodeWolf',challenge_data:challenge,project_snapshot:files,automatic_results:tests,automatic_score:automaticScore,ai_score:aiScore,final_score:finalScore,passed,ai_feedback:feedback,common_errors:errors,generation_model:'BYOK'});if(error)throw error;await logLearningEvent(passed?'challenge_passed':'challenge_failed',{skillId:challenge.skillId,lessonId:challenge.lessonCloudId,metadata:{score:finalScore}})}
export async function createAssessmentSession(){const u=await user();if(!u)return null;const {data:existing}=await supabase.from('assessment_sessions').select('id').eq('owner_id',u.id).in('status',['interview','challenge']).maybeSingle();if(existing)return existing.id;const {data,error}=await supabase.from('assessment_sessions').insert({owner_id:u.id,status:'interview'}).select('id').single();if(error)throw error;return data.id}
export async function updateAssessment(id,payload){const u=await user();if(!u||!id)return;const {error}=await supabase.from('assessment_sessions').update(payload).eq('id',id).eq('owner_id',u.id);if(error)throw error}
export async function listMyLessons(limit=30){const u=await user();if(!u)return [];const {data,error}=await supabase.from('lessons').select('id,external_id,skill_id,title,difficulty,estimated_minutes,xp_reward,objectives,slides,status,current_slide,created_at,completed_at').eq('owner_id',u.id).order('created_at',{ascending:false}).limit(limit);if(error)throw error;return data||[]}
export async function logLearningEvent(eventType,{skillId=null,lessonId=null,metadata={}}={}){const u=await user();if(!u)return;await supabase.from('learning_events').insert({owner_id:u.id,event_type:eventType,skill_id:skillId,lesson_id:lessonId,metadata})}
