let curriculumCache;
export async function loadCurriculum(){if(curriculumCache)return curriculumCache;const r=await fetch('/data/curriculum.json');if(!r.ok)throw Error('Programme indisponible');curriculumCache=await r.json();return curriculumCache}
export function allSkills(curriculum){return curriculum.tracks.flatMap(t=>t.levels.flatMap(l=>l.skills.map(s=>({...s,level:l.id,track:t.id}))))}
export function createLearningState(existing={}){return {version:1,skills:{},lessonHistory:[],currentSkill:null,...existing}}
export function skillState(state,id){return state.skills[id]||{mastery:0,attempts:0,quizCorrect:0,quizTotal:0,challengesPassed:0,commonErrors:[],lastPracticedAt:null}}
export function prerequisitesMet(skill,state){return (skill.prerequisites||[]).every(id=>skillState(state,id).mastery>=55)}
export function recommendNextSkill(curriculum,state,profile={}){const skills=allSkills(curriculum),available=skills.filter(s=>prerequisitesMet(s,state));const unmastered=available.filter(s=>skillState(state,s.id).mastery<80);if(!unmastered.length)return skills.find(s=>skillState(state,s.id).mastery<100)||skills[0];return unmastered.sort((a,b)=>{const sa=skillState(state,a.id),sb=skillState(state,b.id);const reviewA=sa.attempts&&sa.mastery<55?-25:0,reviewB=sb.attempts&&sb.mastery<55?-25:0;return (a.difficulty*10+sa.mastery+reviewA)-(b.difficulty*10+sb.mastery+reviewB)})[0]}
export function validateLesson(input,expectedSkill){const errors=[];if(!input||typeof input!=='object')return {ok:false,errors:['Réponse non structurée']};if(typeof input.title!=='string'||input.title.length<5)errors.push('Titre absent');if(input.skillId!==expectedSkill.id)errors.push('Compétence incorrecte');if(!Array.isArray(input.objectives)||input.objectives.length<1)errors.push('Objectifs absents');if(!Number.isFinite(Number(input.estimatedMinutes)))errors.push('Durée invalide');if(!Array.isArray(input.slides)||input.slides.length<6||input.slides.length>10)errors.push('La leçon doit avoir 6 à 10 slides');const allowed=['concept','example','quiz','challenge','recap'];let quiz=0,challenge=0;(input.slides||[]).forEach((s,i)=>{if(!allowed.includes(s.type))errors.push(`Slide ${i+1}: type invalide`);if(!s.title||(!(s.content||s.question)))errors.push(`Slide ${i+1}: contenu absent`);if(s.type==='quiz'){quiz++;if(!Array.isArray(s.choices)||s.choices.length<2||!Number.isInteger(s.answer)||s.answer<0||s.answer>=s.choices.length)errors.push(`Quiz ${i+1}: réponses invalides`)}if(s.type==='challenge'){challenge++;if(!Array.isArray(s.tests)||s.tests.length<2)errors.push('Le défi doit inclure au moins 2 tests')}});if(quiz<2)errors.push('Au moins 2 quiz requis');if(challenge!==1)errors.push('Un unique défi est requis');if(input.slides?.at(-1)?.type!=='challenge')errors.push('Le défi doit terminer la leçon');return {ok:errors.length===0,errors}}
export function recordQuiz(state,skillId,correct){const s={...skillState(state,skillId)};s.attempts++;s.quizTotal++;if(correct)s.quizCorrect++;const accuracy=s.quizTotal?s.quizCorrect/s.quizTotal:0;s.mastery=Math.max(0,Math.min(100,Math.round(s.mastery*.72+accuracy*100*.28)));s.lastPracticedAt=new Date().toISOString();state.skills[skillId]=s;return state}
export function recordChallenge(state,skillId,{passed,score=0,errors=[]}){const s={...skillState(state,skillId)};s.attempts++;if(passed)s.challengesPassed++;s.mastery=Math.max(0,Math.min(100,Math.round(s.mastery*.55+score*.45)));s.commonErrors=[...new Set([...errors,...s.commonErrors])].slice(0,5);s.lastPracticedAt=new Date().toISOString();state.skills[skillId]=s;return state}
export function lessonPrompt(skill,state,profile){const status=skillState(state,skill.id);return `Tu es l'ingénieur pédagogique de CodeWolf. Génère une leçon en français strictement centrée sur la compétence ${JSON.stringify(skill)}. Profil: ${JSON.stringify(profile)}. Maîtrise actuelle: ${JSON.stringify(status)}. Retourne UNIQUEMENT du JSON valide: {"id":"unique","skillId":"${skill.id}","title":"...","difficulty":${skill.difficulty},"objectives":["..."],"estimatedMinutes":15,"xp":80,"slides":[{"type":"concept|example|quiz|recap|challenge","title":"...","content":"Markdown","code":"optionnel","question":"quiz seulement","choices":["quiz"],"answer":0,"hint":"...","tests":[{"type":"contains","file":"index.html","value":"<main"}] }]}. Contraintes: 6 à 10 slides; 2 quiz minimum; exemples exacts; aucune notion hors prérequis; dernière slide = un seul challenge pratique avec 2 à 5 tests simples, chacun utilisant type contains, notContains ou regex et ciblant index.html, style.css ou script.js.`}
export function saveLearningState(state){localStorage.setItem('codewolf_learning_state',JSON.stringify(state))}
export function loadLearningState(){try{return createLearningState(JSON.parse(localStorage.getItem('codewolf_learning_state')||'{}'))}catch{return createLearningState()}}
